stages:
  - build
  - postbuild
  - scan
  
build_project:
  stage: build
  script:
    - xcodebuild clean -project Connect.xcodeproj -scheme TestApp | xcpretty
    - xcodebuild test -project Connect.xcodeproj -scheme TestApp -derivedDataPath derivedData -destination 'platform=iOS Simulator,name=iPhone 12 Pro,OS=latest' | xcpretty
  artifacts:
    name: "derived-data"
    paths:
      - derivedData/
    expire_in: 1 days
  tags:
    - xcode

coverage:
  stage: postbuild
  script:
    - slather coverage -s
    - slather
    - swiftlint > sonar-reports/swiftlint.txt
  artifacts:
    when: always
    reports:
      cobertura: sonar-reports/cobertura.xml
    paths:
       - sonar-reports
    expire_in: 1 days
  tags:
    - xcode
    
sonarqube:
  stage: scan
  script:
    - sonar-scanner
  tags:
    - xcode
